# Generated by Django 5.2.17 on 2026-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_branchpage_delete_ministrypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(choices=[('About', 'About'), ('Branches', 'Branches'), ('Events', 'Events'), ('Community', 'Community'), ('Music', 'Music'), ('Media', 'Media'), ('Magazine', 'Magazine'), ('Contact', 'Contact')], max_length=50)),
                ('subheading', models.CharField(choices=[('About', 'About Church'), ('About', 'Church History'), ('About', 'Branches'), ('Branches', 'CSI Christ Church, Kambenery'), ('Branches', 'CSI Christ Church, Sundarapandiyapuram'), ('Branches', 'CSI Rhenius Memorial Church, Bharathi Nagar'), ('Branches', 'CSI Christ Church, Poigai-Kovilaandanoor'), ('Events', 'Upcoming Events'), ('Events', 'Church Activities'), ('Events', 'Important Events'), ('Events', 'Special Festivals'), ('Events', 'Prayer Meetings'), ('Events', 'Camps'), ('Events', 'Retreats'), ('Events', 'Missionaries Place Travel'), ('Community', 'Sunday School'), ('Community', 'Youth Fellowship'), ('Community', "Women's Fellowship"), ('Community', "Men's Fellowship"), ('Music', 'Keerthanai Songs'), ('Music', 'K.V. Songs'), ('Music', 'New Songs'), ('Music', 'Music Training'), ('Media', 'Short Videos'), ('Media', 'Long Videos'), ('Media', 'Live'), ('Magazine', 'Magazine Issue'), ('Magazine', 'Magazine Article'), ('Magazine', 'Bible Verse'), ('Magazine', 'Magazine Photo'), ('Contact', 'Contact'), ('Contact', 'Prayer Requests'), ('Contact', 'Visit the Church')], max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section-content/')),
                ('media_url', models.URLField(blank=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subheading Content',
                'verbose_name_plural': 'Subheading Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
