# Generated by Django 5.2.17 on 2026-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sectioncontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='subheading',
            field=models.CharField(choices=[('About Church', 'About Church'), ('Church History', 'Church History'), ('Branches', 'Branches'), ('CSI Christ Church, Kambenery', 'CSI Christ Church, Kambenery'), ('CSI Christ Church, Sundarapandiyapuram', 'CSI Christ Church, Sundarapandiyapuram'), ('CSI Rhenius Memorial Church, Bharathi Nagar', 'CSI Rhenius Memorial Church, Bharathi Nagar'), ('CSI Christ Church, Poigai-Kovilaandanoor', 'CSI Christ Church, Poigai-Kovilaandanoor'), ('Upcoming Events', 'Upcoming Events'), ('Church Activities', 'Church Activities'), ('Important Events', 'Important Events'), ('Special Festivals', 'Special Festivals'), ('Prayer Meetings', 'Prayer Meetings'), ('Camps', 'Camps'), ('Retreats', 'Retreats'), ('Missionaries Place Travel', 'Missionaries Place Travel'), ('Sunday School', 'Sunday School'), ('Youth Fellowship', 'Youth Fellowship'), ("Women's Fellowship", "Women's Fellowship"), ("Men's Fellowship", "Men's Fellowship"), ('Keerthanai Songs', 'Keerthanai Songs'), ('K.V. Songs', 'K.V. Songs'), ('New Songs', 'New Songs'), ('Music Training', 'Music Training'), ('Short Videos', 'Short Videos'), ('Long Videos', 'Long Videos'), ('Live', 'Live'), ('Magazine Issue', 'Magazine Issue'), ('Magazine Article', 'Magazine Article'), ('Bible Verse', 'Bible Verse'), ('Magazine Photo', 'Magazine Photo'), ('Contact', 'Contact'), ('Prayer Requests', 'Prayer Requests'), ('Visit the Church', 'Visit the Church')], max_length=200),
        ),
    ]
